---
install_backend: true
install_mq: true
patch_etc_hosts: true


mq_port: 5672
mq_admin_username: admin
mq_admin_password: adminmdppwd

mq_splash_username: splash
mq_splash_password: mdptest
mq_splash_vhost: splash

pushgateway_host: localhost
pushgateway_port: 9091


redis_host: localhost
redis_port: 6379
redis_base: 1
redis_password: redismdp
