- name : BACKEND install service (Redis)
  package:
    pkg: redis-server
    state: present

- name: BACKEND Configuration
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: root
    group: root
    mode: 0644
  notify: restart Redis
