---
- name : SPLASH install infra (ruby)
  package:
    pkg: ruby
    state: present

- name : SPLASH install Splash (gem)
  gem:
    name: prometheus-splash
    state: present
    user_install: no

- name: SPLASH Check if setup done
  stat:
    path: /etc/splash.yml
  register: stat_result

- name: SPLASH Installation
  shell: splash conf set
  when: not stat_result.stat.exists

- name: SPLASH Configuration
  template:
    src: splash.yml.j2
    dest: /etc/splash.yml
    owner: root
    group: root
    mode: 0644
  notify: restart Splash

- name: SPLASH Check if Systemd service installed
  stat:
    path: /etc/systemd/system/splashd.service
  register: stat_splash_result

- name: SPLASH Install systemd service
  shell: splash conf service
  when: not stat_splash_result.stat.exists

- name: SPLASH Splashd running
  service:
    name: splashd
    state: started
    enabled: yes

- name:  SPLASH LogRotate template
  template:
    src: logrotate.splash.j2
    dest: /etc/logrotate.d/splash
    owner: root
    group: root
    mode: 0644
