:splash:
  :templates:
    :execution: /etc/splash_execution_report.tpl
  :logs:
    - :log: /tmp/test
      :pattern: ERROR
    - :log: /var/log/message
      :pattern: error
  :prometheus:
    :pushgateway:
      :host: "localhost"
      :port: 9091
  :commands:
    :false_test:
      :desc: test command
      :command: false
  :daemon:
    :user: daemon
    :group: daemon
    :process_name: "Splash : Prometheus logs monitoring."
    :paths:
      :pid_path: /tmp
      :trace_path: /tmp/splash
    :files:
      :stdout_trace: stdout.txt
      :stderr_trace: stderr.txt
      :pid_file: splash.pid
