:splash:
  :templates:
    :execution:
      :path: /etc/splash_execution_report.tpl
      :tokens:
        - :date
        - :cmd_name
        - :cmd_line
        - :stdout
        - :stderr
        - :desc
        - :status
  :logs:
    - :log: /tmp/test
      :pattern: ERROR
    - :log: /var/log/message
      :pattern: error
  :prometheus:
    :pushgateway:
      :host: "localhost"
      :port: 9091
  :commands:
    :false_test:
      :desc: "test command"
      :command: "false"
    :ls_slash_tmp:
      :desc: list file in /tmp
      :command: ls -al /tmp
      :user: daemon
  :daemon:
    :user: daemon
    :group: daemon
    :process_name: "Splash : Prometheus logs monitoring."
    :paths:
      :pid_path: /tmp
      :trace_path: /tmp/splash
    :files:
      :stdout_trace: stdout.txt
      :stderr_trace: stderr.txt
      :pid_file: splash.pid
