---
- name: PREPARE TESTING ocalhost entries for test
  hosts:
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: 127.0.0.1 localhost  {{ groups['backend'][0] }} {{ groups['mq'][0] }} {{ groups['splash_nodes'][0] }} {{ groups['supervision_master'][0] }} {{ groups['supervision_gateway'][0] }}
    owner: root
    group: root
    mode: '0644'
  when: patch_etc_hosts




- name: Deploy RabbitMQ
  #become: yes
  hosts: mq
  tasks:
  - include_role:
      name: mq
    when: install_mq

- name:  Deploy Backend
  become: yes
  hosts: backend
  tasks:
  - include_role:
      name: backend
    when: install_backend

- name: Deploy Supervision Master
  become: yes
  hosts: supervision_master
  roles:
    - supervision_master

- name: Deploy Supervision Gateway
  become: yes
  hosts: supervision_gateway
  roles:
    - supervision_gateway

- name: Deploy Splash
  become: yes
  hosts: splash_nodes
  roles:
    - splash
