---
- name: Deploy RabbitMQ
  #become: yes
  hosts: mq
  tasks:
  - include_role:
      name: mq
    when: "mq == True"

- name:  Deploy Backend
  become: yes
  hosts: backend
  tasks:
  - include_role:
      name: backend
    when: "backend == True"

- name: Deploy Supervision Master
  become: yes
  hosts: supervision_master
  roles:
    - supervision_master

- name: Deploy Supervision Gateway
  become: yes
  hosts: supervision_gateway
  roles:
    - supervision_gateway

- name: Deploy Splash
  become: yes
  hosts: splash_nodes
  roles:
    - splash
