# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 9090, host: 9090 # prometheus
  config.vm.network "forwarded_port", guest: 9091, host: 9091 # pushgateway
  config.vm.network "forwarded_port", guest: 9093, host: 9093 # alertmanager
  config.vm.network "forwarded_port", guest: 6379, host: 6379 # redis
  config.vm.network "forwarded_port", guest: 5672, host: 5672 # rabbitmq

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-add-repository --yes --update ppa:ansible/ansible
     apt-get install -y git ansible
     git clone https://github.com/Ultragreen/prometheus-splash.git
     cd prometheus-splash/templates/ansible-splash
     ansible-playbook -i inventory.dev deploy.yml

   SHELL
end
