# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-add-repository --yes --update ppa:ansible/ansible
     apt-get install -y git ansible
     git clone https://github.com/Ultragreen/prometheus-splash.git
     cd prometheus-splash/templates/ansible-splash
     ansible-playbook -i inventory.dev ddeplay.yml
 
   SHELL
end
